[package]
name = "flicks"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"
dotenv_codegen = "0.15.0"
flicks-discord = { path = "./src/core/flicks-discord", version = "=0.1.0" }
flicks-telegram = { path = "./src/core/flicks-telegram", version = "=0.1.0" }
file-system-provider = { path = "./src/file-system-provider", version = "=0.1.0" }

[dev-dependencies]
tempfile = "3.1.0"
