[package]
name = "flicks-telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
grammers-client = "0.4.0"
grammers-session = "0.4.0"
grammers-tl-types = "0.4.0"
flicks-core = { path = "../flicks-core", version = "=0.1.0" }