[package]
name = "flicks-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
serenity = "0.11"
flicks-core = { path = "../flicks-core", version = "=0.1.0" }
async-trait = "0.1.73"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }